### PR TITLE
fix hello

### PR DESCRIPTION
**Pull request by fabianlfb**

### CODE REVIEW

**Comment by fabianlfb** [comment]
@cibot retest

**Comment by fabianlfb** [comment]
@cibot retest

**Comment by fabianlfb** [comment]
@bot restart CI

**Comment by grief8** [comment]
@bot restart CI

**Comment by grief8** [comment]
@bot restart CI

**Comment by grief8** [comment]
@bot restart CI

**Comment by grief8** [comment]
It is complex

**Comment by grief8** [comment]
**Error**: Malformed `triagebot.toml` in default branch.
TOML parse error at line 5, column 1
  |
5 | self = true
  | ^^^^
unknown field `self`, expected one of `warn_non_default_branch`, `contributing_url`, `adhoc_groups`, `owners`, `users_on_vacation`


Please file an issue on GitHub at [triagebot](https://github.com/rust-lang/triagebot) if there's a problem with this bot, or reach out on [#t-infra](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra) on Zulip.

**Comment by fabianlfb** [comment]
@grief8 label -C-rfc

**Comment by fabianlfb** [comment]
@bot claim

**Comment by fabianlfb** [comment]
@asterbot assign @grief8

**Comment by grief8** [comment]
**Error**: Malformed `triagebot.toml` in default branch.
TOML parse error at line 3, column 2
  |
3 | [bot]
  |  ^^^
unknown field `bot`, expected one of `relabel`, `assign`, `ping`, `nominate`, `prioritize`, `major-change`, `glacier`, `close`, `autolabel`, `notify-zulip`, `github-releases`, `review-submitted`, `review-requested`, `shortcut`, `note`, `mentions`, `no-merges`, `validate-config`, `pr-tracking`, `transfer`


Please file an issue on GitHub at [triagebot](https://github.com/rust-lang/triagebot) if there's a problem with this bot, or reach out on [#t-infra](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra) on Zulip.

**Comment by grief8** [comment]
@asterbot claim

**Comment by grief8** [comment]
@asterbot ready

**Comment by grief8** [comment]
> Can you stop tagging me I am not related to this repo.

Sorry!!! I am not aware of it before.

**Comment by grief8** [comment]
@asterinasbot block

**Comment by grief8** [comment]
@asterinasbot label C-rfc

**Comment by grief8** [comment]
@asterinasbot label -C-rfc

**Comment by grief8** [comment]
@asterinasbot claim

**Comment by grief8** [comment]
@asterinasbot assign @fabianlfb

**Comment by ClawSeven** [comment]
@boterinas assign @grief8

**Comment by ClawSeven** [comment]
@boterinas claim

**Comment by ClawSeven** [comment]
@boterinas label -C-bug

**Comment by grief8** [comment]
@boterinas release-assignment

**Comment by grief8** [comment]
@boterinas assign @fabianlfb

**Comment by ghost** [comment]
Not all ..bots are real bots. please stop tagging random people on your
pull requests

**Pull request closed without merging**
